language: objective-c
install:
- mkdir tmp && cd tmp
- ../scripts/install_libltc.sh
- ls -la
- ../scripts/install_sdl.sh
- ../scripts/bootstrap.sh
- export PATH=$PATH:/usr/local/opt/qt5/bin
script:
# Build AutoTest
- mkdir AutoTest && cd AutoTest
- qmake ../../tests/AutoTest/AutoTest.pro
- make
# Run AutoTest
- ./AutoTest
- cd .. 
# Build Joker
- mkdir Joker && cd Joker
- qmake ../../app/Joker/Joker.pro
- make
- cd ..
- cd ..
- ./scripts/doxygen.sh
- ./scripts/uncrustify.sh
notifications:
 irc: "phonations.com#joker"
 email: false

