language: cpp
branches:
  except:
    - /^skipthisbranch$/
env:
  global:
  - JOKER_RELEASE_PATH=$HOME
  - TESTS_RELEASE_PATH=$HOME
  - COVERITY_SCAN_PROJECT_NAME=Phonations/Joker
  - COVERITY_SCAN_SCRIPT=https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh
  - COVERITY_SCAN_NOTIFICATION_EMAIL=martin@phonations.com
  - COVERITY_SCAN_BRANCH_PATTERN=master
  - COVERITY_SCAN_BUILD_COMMAND=make
  - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cov-configure --comptype clangcxx --compiler clang++"
  - secure: YlyaETwveWXOT1wpOz68Vp8Pj1zZ5u44ppOabNw/Xe4M8ZHdPy3QkmyB7wTeUgNjlHzkW23aOOzTk8bm5wxS1iQRxHsQ/DnZd0TcULPuTY9+yO2L/Wkwk6quFBqGlkT8h2v4xkRDyshG8OxF6eqeeq5Cflt/LOhx+MnJqse9EzQ=
matrix:
  include:
    - os: osx
      env:
        - JOB=UNCRUSTIFY
    - os: osx
      env:
        - JOB=DOXYGEN
    - os: linux
      env:
        - JOB=BUILD_RELEASE_JOKER
        - QTVER=551
    - os: osx
      env:
        - JOB=BUILD_RELEASE_JOKER
        - QTVER=551
    - os: osx
      env:
        - JOB=BUILD_COVERITY_JOKER
        - QTVER=532
    - os: osx
      env:
        - JOB=BUILD_SPEC_BANDIT
        - QTVER=551
    - os: osx
      env:
        - JOB=BUILD_RELEASE_LTCTOOL
        - QTVER=551
    - os: osx
      env:
        - JOB=BUILD_RELEASE_MIDITOOL
        - QTVER=551
    - os: osx
      env:
        - JOB=BUILD_RELEASE_ALL_TESTS
        - QTVER=551
before_install:
- export SHORT_VER=`echo $QTVER | cut -b1-2`
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == linux ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt${QTVER};
  fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == linux ]]; then sudo apt-get -qy update; fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == osx && $QTVER != 532 ]]; then brew update; fi
install:
- git submodule update --init --recursive
- if [[ "$JOB" == UNCRUSTIFY ]]; then brew install uncrustify; fi
- if [[ "$JOB" == DOXYGEN ]]; then brew install doxygen; fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == linux ]]; then sudo apt-get -qy
  install qt${SHORT_VER}base qt${SHORT_VER}xmlpatterns libboost-all-dev; fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == linux ]]; then . /opt/qt${SHORT_VER}/bin/qt${SHORT_VER}-env.sh;
  fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == linux ]]; then export QMAKESPEC=linux-clang;
  fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == osx ]]; then brew install qt5; fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == osx ]]; then brew link --force qt5;
  fi
- if [[ "$JOB" == BUILD_* && "$TRAVIS_OS_NAME" == osx ]]; then export QMAKESPEC=macx-clang;  fi
- if [[ "$JOB" == BUILD_* ]]; then scripts/install_sdl.sh; fi
- if [[ "$JOB" == BUILD_* ]]; then scripts/install_ltc.sh; fi
- if [[ "$JOB" == BUILD_* ]]; then scripts/install_ffmpeg.sh; fi
- if [[ "$JOB" == BUILD_* ]]; then scripts/install_portaudio.sh; fi
- if [[ "$JOB" == BUILD_* ]]; then scripts/install_rtmidi.sh; fi
- if [[ "$JOB" == BUILD_SPEC_* ]]; then sudo pip install cpp-coveralls; fi
script:
- if [[ "$JOB" == UNCRUSTIFY ]]; then ./scripts/uncrustify.sh; fi
- if [[ "$JOB" == DOXYGEN ]]; then ./scripts/doxygen.sh; fi
- if [[ "$JOB" == BUILD_SPEC_BANDIT ]]; then qmake specs/AllSpecs/AllSpecs.pro; fi
- if [[ "$JOB" == BUILD_*_JOKER ]]; then qmake app/Joker/Joker.pro; fi
- if [[ "$JOB" == BUILD_RELEASE_LTCTOOL ]]; then qmake app/LTCTool/LTCTool.pro; fi
- if [[ "$JOB" == BUILD_RELEASE_MIDITOOL ]]; then qmake app/MidiTool/MidiTool.pro;
  fi
- if [[ "$JOB" == BUILD_RELEASE_ALL_TESTS ]]; then qmake tests/tests.pro; fi
- if [[ "$JOB" == BUILD_* && "$JOB" != BUILD_COVERITY_JOKER ]]; then make; fi
- if [[ "$JOB" == BUILD_COVERITY_JOKER && "$TRAVIS_BRANCH" == "$COVERITY_SCAN_BRANCH_PATTERN" ]]; then curl -s "$COVERITY_SCAN_SCRIPT" | bash; fi
- if [[ "$JOB" == BUILD_SPEC_BANDIT ]]; then ./AllSpecs; fi
- if [[ "$JOB" == BUILD_RELEASE_JOKER ]]; then make installer; fi
- if [[ "$JOB" == BUILD_RELEASE_JOKER ]]; then export RELEASED_PACKAGE_FILENAME=$(ls
  -1 Joker_v*.dmg); fi
- if [[ "$JOB" == BUILD_RELEASE_JOKER ]]; then echo "RELEASED_PACKAGE_FILENAME:";
  fi
- if [[ "$JOB" == BUILD_RELEASE_JOKER ]]; then echo $RELEASED_PACKAGE_FILENAME; fi
after_success:
- if [[ "$TRAVIS_OS_NAME" == osx ]] && [[ "$JOB" == BUILD_AUTOTEST ]]; then coveralls
  -E .+/moc_.+ -E .+/ui_.+ -E .+\.app -E .+/tests/.+ -E .+/app/.+ -E .+/specs/.+ --verbose;
  fi
- if [[ "$TRAVIS_OS_NAME" == osx ]] && [[ "$JOB" == BUILD_RELEASE_JOKER ]]; then ./scripts/upload.sh
  *.dmg; fi
after_failure:
- if [[ "$TRAVIS_OS_NAME" == osx ]] && [[ "$JOB" == BUILD_SPEC_BANDIT ]]; then ./scripts/upload.sh
  *.result.bmp; fi
notifications:
  email: false
  irc:
    channels: phonations.com#joker
    on_success: always
  webhooks:
    urls: https://webhooks.gitter.im/e/9e468ed6125989020262
    on_success: always
  slack:
    secure: CVzAyvFoT5LFnODOVooG21txFq7B75nER+tLiGr4GFTimKWPb9mdmrqxvaHyJdp0RBtdLFyuWCeA2Gxi1SarPSCstlw0HP0rP0w27gEwVmt2E1xO4RUzHv5JKdbogKNHZJfdTw5VVAgzGNhCRBw2pL33CV0KwJ20lfJUOcg0JY8=
deploy:
  provider: releases
  api_key:
    secure: DTPxxREDO8+Pi/cnqKr1nce9FxJ3AUY7h4S9gHt3S2vBkrlZM4vD4GLXCVjbZuSpnqkTTAiGhUiYEN8jiF3pjStKKlEl2w537cDpoSl1ZAB5G+G3PKTBxG5MhRMZkTEgYFvtx/VPpvleQ4C8cMosogQk7iBwwuk19FLbcL0/kL4=
  file: "${RELEASED_PACKAGE_FILENAME}"
  skip_cleanup: true
  on:
    tags: true
    condition: "$JOB = BUILD_RELEASE_JOKER && $TRAVIS_OS_NAME = osx"
