language: objective-c
install:
- scripts/install_sdl.sh
- scripts/bootstrap.sh
- scripts/install_libltc.sh
- export PATH=$PATH:/usr/local/opt/qt5/bin
#- export JOKER_RELEASE_PATH=$HOME

- brew install pyenv
- echo $PATH
- eval "$(pyenv init -)"
- echo $PATH
- pyenv install 2.7.6
- echo $PATH
- pyenv global 2.7.6
- echo $PATH
- pyenv rehash
- echo $PATH
- pip install cpp-coveralls
- echo $PATH
- pyenv rehash
- echo $PATH
- pip install cpp-coveralls --use-mirrors
- echo $PATH

script:
- qmake -v
#- qmake all.pro
- qmake tests/AutoTest/AutoTest.pro
- make
#- cd tests/AutoTest
- "./AutoTest"
#- cd ../..
#- mkdir Joker && cd Joker
#- qmake ../../Joker/app/Joker/Joker.pro
#- make
#- cd ../Joker
#- "./scripts/doxygen.sh"
#- "./scripts/uncrustify.sh"
after_success:
- coveralls -E .+/moc_.+ -E .+/ui_.+
#- "./scripts/update-gh-pages.sh"
notifications:
  flowdock:
    secure: CnvMZuPXcFS6FQ17QYgtWsp9GUTbidjulsmpzbVh9S2zN2xVjGEMKe8KafPa55ugFYbYudCt7w20+wJO4OomYFQxgKAtJuGHZQ9jIfv0vl2sAcuzdaJY6aCFDtL4DFpAjGp8qwkZ0Mtx1xFgqyMcF/8eHfQm7bGO+ahmI5f9Jbc=
  email: false
env:
  global:
    secure: StCptdbX5mPsWDLvwtRS8R0IP2t0ZaPUpRHtnVQbooMyskwWHOiM809iGFoUNyvsZQiPl/0psWjlpXpWm+NBmChj/ADksx9PhFg8WKya3uTLQ2bJkGo9dtW7y1BQ38kDpqrKVjn1zTKF1lZvd3+09KzNmmjAAcoxlD6rqssP7Rw=
