language: objective-c
env:
- JOB="UNCRUSTIFY"
- JOB="DOXYGEN"
#- JOB="BUILD_AUTOTEST"
#- JOB="BUILD_JOKER"
#- JOB="BUILD_ALL"
install:
- if [[ "$JOB" == "UNCRUSTIFY" ]]; then brew install uncrustify; fi
- if [[ "$JOB" == "DOXYGEN" ]]; then brew install doxygen; fi
#- scripts/install_sdl.sh
#- scripts/bootstrap.sh
#- scripts/install_libltc.sh
#- export PATH=$PATH:/usr/local/opt/qt5/bin
#- export JOKER_RELEASE_PATH=$HOME
#- export TESTS_RELEASE_PATH=$HOME
#- eval "$(pyenv init -)"

script:
- if [[ "$JOB" == "UNCRUSTIFY" ]]; then ./scripts/uncrustify.sh; fi
- if [[ "$JOB" == "DOXYGEN" ]]; then ./script/doxygen.sh; fi
#- qmake all.pro
#- qmake tests/AutoTest/AutoTest.pro
#- make
#- ./AutoTest
#- coveralls -E .+/moc_.+ -E .+/ui_.+ -E .+\.app -E .+/tests/.+ -E .+/app/.+ --verbose
#after_failure:
#- curl --form "file=@tests/AutoTest/graphicStripTestResult.bmp" http://phonations.com/feedback/serv.php
#- curl --form "file=@tests/AutoTest/swensonTestResult.bmp" http://phonations.com/feedback/serv.php
#- curl --form "file=@tests/AutoTest/arialTestResult.bmp" http://phonations.com/feedback/serv.php
#- curl --form "file=@tests/AutoTest/bedizenTestResult.bmp" http://phonations.com/feedback/serv.php
#- curl --form "file=@tests/AutoTest/weblysleekuilTestResult.bmp" http://phonations.com/feedback/serv.php
notifications:
  flowdock:
    secure: CnvMZuPXcFS6FQ17QYgtWsp9GUTbidjulsmpzbVh9S2zN2xVjGEMKe8KafPa55ugFYbYudCt7w20+wJO4OomYFQxgKAtJuGHZQ9jIfv0vl2sAcuzdaJY6aCFDtL4DFpAjGp8qwkZ0Mtx1xFgqyMcF/8eHfQm7bGO+ahmI5f9Jbc=
  email: false
