#language: objective-c
install:
- "scripts/bootstrap.sh"
- "scripts/install_libltc.sh"
- "scripts/install_sdl.sh"
- export PATH=$PATH:/usr/local/opt/qt5/bin
- export JOKER_RELEASE_PATH=$HOME
script:
- qmake -v
- mkdir tmp && cd tmp
- mkdir AutoTest && cd AutoTest
- qmake ../../tests/AutoTest/AutoTest.pro
- make
- "./AutoTest"
- cd ..
- mkdir Joker && cd Joker
- qmake ../../app/Joker/Joker.pro
- make
- cd ..
- cd ..
- mkdir doc
- "./scripts/doxygen.sh"
#- "./scripts/uncrustify.sh"
after_success:
- coveralls --exclude /usr/local --exclude tmp/Joker --exclude tests --build-root
  tmp/AutoTest -E .+/moc_.+ -E .+/ui_.+
- ./scripts/update-gh-pages.sh
notifications:
  irc: phonations.com#joker
  flowdock: d48132b46c7d11203f85818bc626f2bf
  email: false
env:
  global:
    secure: StCptdbX5mPsWDLvwtRS8R0IP2t0ZaPUpRHtnVQbooMyskwWHOiM809iGFoUNyvsZQiPl/0psWjlpXpWm+NBmChj/ADksx9PhFg8WKya3uTLQ2bJkGo9dtW7y1BQ38kDpqrKVjn1zTKF1lZvd3+09KzNmmjAAcoxlD6rqssP7Rw=
